[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#E3CAA8"

# Background color for the main content area.
backgroundColor = "#1C1C1A"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#373B70"

# Color used for almost all text.
textColor = "#D3BA84"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font="monospace"

[client]
# Controls whether the default sidebar page navigation in a multipage app is displayed.
showSidebarNavigation = false
